---
language: ruby
rvm:
- 2.2.5

install:
  - bundle install
  - gem install html-proofer
  - sudo pip install pytest

script:
  - jekyll build
  - htmlproofer ./_site
  - cp _site-validation/site-validation.md _pages
  - jekyll build
  - pytest
